add Actions File

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,6 +46,15 @@ jobs:
           echo "Deploying to server..."
           echo "SERVER_IP: $SERVER_IP"
           echo "SERVER_USER: $SERVER_USER"
-          sshpass -p "$SERVER_PASSWORD" ssh "$SERVER_USER@$SERVER_IP" "mkdir -p ~/myapp && rm -rf ~/myapp/*"
-          sshpass -p "$SERVER_PASSWORD" scp -r build/libs/* "$SERVER_USER@$SERVER_IP:~/myapp/"
-          sshpass -p "$SERVER_PASSWORD" ssh "$SERVER_USER@$SERVER_IP" "cd ~/myapp && java -jar macros_system.jar"
+          
+          # Создание директории и очистка
+          sshpass -p "$SERVER_PASSWORD" ssh "$SERVER_USER@$SERVER_IP" "mkdir -p ~/myapp && rm -rf ~/myapp/*" || echo "Failed to create or clear directory on server"
+
+          # Копирование файлов
+          sshpass -p "$SERVER_PASSWORD" scp -r build/libs/* "$SERVER_USER@$SERVER_IP:~/myapp/" || echo "Failed to copy files to server"
+
+          # Проверка наличия файла
+          sshpass -p "$SERVER_PASSWORD" ssh "$SERVER_USER@$SERVER_IP" "ls ~/myapp || echo 'Failed to list files in ~/myapp'" 
+
+          # Запуск приложения
+          sshpass -p "$SERVER_PASSWORD" ssh "$SERVER_USER@$SERVER_IP" "cd ~/myapp && java -jar macros_system.jar || echo 'Failed to run the jar file'"
