add Actions File

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,16 +46,15 @@ jobs:
           echo "Deploying to server..."
           echo "SERVER_IP: $SERVER_IP"
           echo "SERVER_USER: $SERVER_USER"
-          
+
           # Создание директории и очистка
           sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "mkdir -p ~/myapp && rm -rf ~/myapp/*" || echo "Failed to create or clear directory on server"
-  
-          # Копирование файлов
+            
+            # Копирование файлов
           sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no -r build/libs/* "$SERVER_USER@$SERVER_IP:~/myapp/" || echo "Failed to copy files to server"
-  
-          # Проверка наличия файла
+            
+            # Проверка наличия файла
           sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "ls ~/myapp || echo 'Failed to list files in ~/myapp'"
-  
-           # Запуск приложения
-          # Запуск приложения
-          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "cd ~/myapp && java -jar MacroSystem-all.jar || echo 'Failed to run the jar file'"
+            
+            # Запуск приложения с логированием
+          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "cd ~/myapp && [ -f MacroSystem-all.jar ] && java -jar MacroSystem-all.jar > app.log 2>&1 || echo 'JAR file not found or failed to run'"
